### ISSUE TITLE
ssl-bump requires https_port instead of http_port.

### ISSUE THREAD

**Issue by ilyaevseev** [jpelias/squid3-ssl-bump#1]
It seems that "http_port 8080 ssl-bump ..." in [squid.conf](../blob/master/squid.conf) and "http_port 3130 transparent ssl-bump ..." in installation article are incorrect.

"https_port ..." should be used for that.

**Comment by shyamkhakhar9** [comment]
@ilyaevseev No we can use http_port 8080 ssl-bump.
Please refer to the following url:
https://wiki.squid-cache.org/Features/SslBump
